### ISSUE TITLE
Update Prismic Nuxt Documentation to account for new Slice Machine Approach

### ISSUE THREAD

**Issue by evolve2k** [prismicio/nuxtjs-website#10]
> Note for anyone reading this before setting up Prismic with Nuxt.. follow [the instructions here](https://www.slicemachine.dev/documentation/nuxt/tutorials) to setup your prismic project to support a much better slices feature, don't clone this repo like I did. 

I've setup my project following from the main prismic website, to setting up prismic with nuxt, to then cloning this repo as my starting point.

After getting started, I've now found out you have a new *better* way to include slices into Prismic Nuxt projects, using your new Slice Machine approach.

Please update this repo and your documentation so that the default project setup includes Slice Machine baked in. 
Otherwise we're doing lots of rework chasing your dev team around their new project ideas.

**I followed this to setup as advised in website documentation**
https://user-guides.prismic.io/en/articles/2831943-nuxt-js-sample-multi-page-website-with-navigation
https://github.com/prismicio/nuxtjs-website

With the benefit of hindsight I should have followed this to setup:
https://www.slicemachine.dev/documentation/nuxt/tutorials
https://github.com/prismicio/slice-machine

Make it one same approach.

**Comment by evolve2k** [comment]
Prismic team, once I've back installed slicemachine into my existing repo cloned from this repo.
How do I update the slices used in my prismic project.

Eg to go from this currently:

![prismic_io_-_brave-energy-systems](https://user-images.githubusercontent.com/114459/88609222-c1b02200-d0c2-11ea-9c70-0e6ed0f3f649.png)


To this that leverages the new slice machine pre-designed slice components:

![prismic_io_-_brave2](https://user-images.githubusercontent.com/114459/88609153-92011a00-d0c2-11ea-9dcc-fd0070b87d8b.png)

![prismic_io_-_brave2](https://user-images.githubusercontent.com/114459/88609264-d7254c00-d0c2-11ea-980c-4d04a443c31a.png)

**Comment by phillysnow** [comment]
Hi Richie,

Thank you for pointing this out. We are working on updating this and plan to implement it with Slice Machine very soon. Once we have done some updates to the Prismic CLI we will add our updates for this project.

**Comment by phillysnow** [comment]
Docs now account for Slice Machine & non Slice Machine. [https://prismic.io/docs/technologies/nuxtjs](https://prismic.io/docs/technologies/nuxtjs)
