### ISSUE TITLE
Edit and Preview not working

### ISSUE THREAD

**Issue by adriano-tirloni** [prismicio/nuxtjs-website#4]
I've been having difficulties setting up the preview and edit button in a Nuxt project.
So I cloned this repo to figured out what I'm doing wrong.
1- Cloned it.
2- npm i
3- Created custom types in my prismic repo. with some dummy data.
4- npm run dev
5- site is running. but no edit or preview button present.
6- added the preview in prismic repo targeting to http://localhost:3000
7- altered a page and clique preview
8- redirected to page (http://localhost:3000/page/dummy) but still in old version and no preview bar or edit button.

As you can see below edit button component is present but preview bar still nowhere.

![image](https://user-images.githubusercontent.com/6390605/61400154-09904c80-a8a6-11e9-9ec9-f39ffcef93f6.png)

![image](https://user-images.githubusercontent.com/6390605/61400259-43615300-a8a6-11e9-9e2c-07f12eb64143.png)

**Comment by adriano-tirloni** [comment]
I just figured it.

Since this is a cookie base system with token you have to allow cookies on chrome.
Not only allow the domain but also click in manage and allow prismic domain and subdomain for it to work properly.

Please, add this to the docs.

**Comment by phillysnow** [comment]
Hi Adriano,

We will add this to our document improvement backlog to make this clearer. 

Thanks,
Phil.
